/**
 * Daftar universitas dan sekolah populer di Indonesia.
 * Digunakan sebagai data saran (autocomplete) pada form Instansi.
 */
export const INSTITUTION_LIST: string[] = [
  // Universitas Negeri (PTN)
  "Universitas Indonesia",
  "Institut Teknologi Bandung",
  "Universitas Gadjah Mada",
  "Institut Pertanian Bogor",
  "Universitas Airlangga",
  "Universitas Diponegoro",
  "Universitas Padjadjaran",
  "Universitas Brawijaya",
  "Universitas Hasanuddin",
  "Universitas Sebelas Maret",
  "Universitas Negeri Yogyakarta",
  "Universitas Negeri Semarang",
  "Universitas Negeri Malang",
  "Universitas Negeri Surabaya",
  "Universitas Pendidikan Indonesia",
  "Institut Teknologi Sepuluh Nopember",
  "Universitas Syiah Kuala",
  "Universitas Sumatera Utara",
  "Universitas Andalas",
  "Universitas Negeri Padang",
  "Universitas Lambung Mangkurat",
  "Universitas Mulawarman",
  "Universitas Udayana",
  "Universitas Mataram",
  "Universitas Nusa Cendana",
  "Universitas Sam Ratulangi",
  "Universitas Pattimura",
  "Universitas Cenderawasih",
  "Universitas Tanjungpura",
  "Universitas Sriwijaya",
  "Universitas Lampung",
  "Universitas Riau",
  "Universitas Jenderal Soedirman",
  "Universitas Pembangunan Nasional Veteran",
  "Institut Teknologi Kalimantan",
  "Institut Teknologi Sumatera",
  "Universitas Trunojoyo Madura",
  "Universitas Sultan Ageng Tirtayasa",
  "Universitas Bengkulu",
  "Universitas Jambi",
  "Universitas Bangka Belitung",
  "Universitas Borneo Tarakan",
  "Universitas Sulawesi Tenggara",
  "Universitas Halu Oleo",

  // Universitas Swasta Terkenal
  "Universitas Bina Nusantara",
  "Universitas Trisakti",
  "Universitas Pelita Harapan",
  "Universitas Atma Jaya",
  "Universitas Tarumanagara",
  "Universitas Mercu Buana",
  "Universitas Gunadarma",
  "Universitas Muhammadiyah Malang",
  "Universitas Muhammadiyah Yogyakarta",
  "Universitas Islam Indonesia",
  "Universitas Islam Negeri Sunan Kalijaga",
  "Universitas Islam Negeri Maulana Malik Ibrahim",
  "Universitas Islam Negeri Syarif Hidayatullah",
  "Universitas Islam Negeri Sunan Gunung Djati",
  "Universitas Kristen Satya Wacana",
  "Universitas Sanata Dharma",
  "Universitas Katolik Indonesia Atma Jaya",
  "Universitas Dian Nuswantoro",
  "Universitas Ahmad Dahlan",
  "Universitas Muhammadiyah Surakarta",
  "Universitas Telkom",
  "Universitas Prasetiya Mulya",
  "Universitas Paramadina",
  "Universitas Esa Unggul",
  "Universitas Bakrie",
  "Universitas Multimedia Nusantara",
  "Universitas Ciputra",
  "Universitas Internasional Semen Indonesia",

  // SMA/SMK Negeri Populer
  "SMA Negeri 1 Jakarta",
  "SMA Negeri 8 Jakarta",
  "SMA Negeri 3 Bandung",
  "SMA Negeri 5 Bandung",
  "SMA Negeri 1 Surabaya",
  "SMA Negeri 5 Surabaya",
  "SMA Negeri 1 Yogyakarta",
  "SMA Negeri 3 Yogyakarta",
  "SMA Negeri 2 Semarang",
  "SMA Negeri 1 Semarang",
  "SMA Negeri 1 Medan",
  "SMA Negeri 1 Makassar",
  "SMA Negeri 1 Denpasar",
  "SMA Negeri 1 Palembang",
  "SMA Negeri 1 Balikpapan",
  "SMA Negeri 1 Padang",
  "SMA Negeri 1 Malang",
  "SMA Negeri 1 Bogor",
  "SMA Negeri 1 Bekasi",
  "SMA Negeri 1 Depok",
  "SMK Negeri 1 Jakarta",
  "SMK Negeri 1 Surabaya",
  "SMK Negeri 2 Bandung",

  // Madrasah
  "Madrasah Aliyah Negeri 1 Jakarta",
  "Madrasah Aliyah Negeri 2 Jakarta",
  "Madrasah Aliyah Negeri Insan Cendekia",
  "Madrasah Aliyah Negeri 1 Yogyakarta",
  "Madrasah Aliyah Negeri 1 Surabaya",
];
